spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/bitdefender?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bitdefender
    password: bitdefender
  jpa:
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.xml
server:
  port: 8080
